# Generated by Django 5.0.10 on 2026-02-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('price', models.PositiveIntegerField(help_text='Amount in Naira')),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial')], default='APARTMENT', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
        ),
    ]
